package misclases;

import controlMySQL.MySqlConn;
import java.awt.Color;
import java.util.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

public class JPanelRegistro extends javax.swing.JPanel {

    /**
     * Creates new form JPanelInicio
     */
    MySqlConn conn;
    private List<JButton> botones;

    public JPanelRegistro(MySqlConn conn) {
        this.conn = conn;
        botones = new ArrayList();
        initComponents();
        StyledDocument doc = this.jTextPane1.getStyledDocument();
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
        doc.setParagraphAttributes(0, doc.getLength(), center, false);
    }

    public JPanelRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHeader = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jSeparatorNombre = new javax.swing.JSeparator();
        jLabelPersonas = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabelPersonas1 = new javax.swing.JLabel();
        jDateChooserIngreso = new com.toedter.calendar.JDateChooser();
        jLabelCiudadOrigen = new javax.swing.JLabel();
        jTextFieldCiudadOrigen = new javax.swing.JTextField();
        jSeparatorCiudadOrig = new javax.swing.JSeparator();
        jSpinner1 = new javax.swing.JSpinner();
        jLabelFechaIngreso = new javax.swing.JLabel();
        jDateChooserSalida = new com.toedter.calendar.JDateChooser();
        jLabelFechaIngreso1 = new javax.swing.JLabel();
        jSeparatorCiudadOrig1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jCheckBoxDosExtra = new javax.swing.JCheckBox();
        jCheckBoxUnaExtra = new javax.swing.JCheckBox();
        jLabelPersonas2 = new javax.swing.JLabel();
        jComboBoxPersonas = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelDisponibles = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/registroHeader.png"))); // NOI18N
        add(jLabelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 145));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldNombre.setFont(new java.awt.Font("Decker", 0, 17)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldNombre.setBorder(null);
        jTextFieldNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldNombre.setSelectionColor(new java.awt.Color(214, 173, 96));
        jTextFieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusLost(evt);
            }
        });
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 280, 30));

        jLabelNombre.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(51, 51, 51));
        jLabelNombre.setText("Nombre:");
        jPanel3.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 150, 30));

        jSeparatorNombre.setBackground(new java.awt.Color(160, 160, 160));
        jPanel3.add(jSeparatorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 280, 10));

        jLabelPersonas.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabelPersonas.setForeground(new java.awt.Color(51, 51, 51));
        jLabelPersonas.setText("Personas:");
        jPanel3.add(jLabelPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 120, 30));

        jComboBoxTipo.setFont(new java.awt.Font("Decker", 0, 17)); // NOI18N
        jComboBoxTipo.setForeground(new java.awt.Color(51, 51, 51));
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sencilla", "Doble", "Suite" }));
        jPanel3.add(jComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 280, 30));

        jLabelPersonas1.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabelPersonas1.setForeground(new java.awt.Color(51, 51, 51));
        jLabelPersonas1.setText("Días a hospedar:");
        jPanel3.add(jLabelPersonas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 150, 30));

        jDateChooserIngreso.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooserIngreso.setForeground(new java.awt.Color(102, 102, 102));
        jDateChooserIngreso.setFont(new java.awt.Font("Decker", 0, 17)); // NOI18N
        jDateChooserIngreso.setMinSelectableDate(new java.util.Date());
        jPanel3.add(jDateChooserIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 190, 30));

        jLabelCiudadOrigen.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabelCiudadOrigen.setForeground(new java.awt.Color(51, 51, 51));
        jLabelCiudadOrigen.setText("Ciudad de origen:");
        jPanel3.add(jLabelCiudadOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 150, 30));

        jTextFieldCiudadOrigen.setFont(new java.awt.Font("Decker", 0, 17)); // NOI18N
        jTextFieldCiudadOrigen.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldCiudadOrigen.setBorder(null);
        jTextFieldCiudadOrigen.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldCiudadOrigen.setSelectionColor(new java.awt.Color(214, 173, 96));
        jTextFieldCiudadOrigen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCiudadOrigenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCiudadOrigenFocusLost(evt);
            }
        });
        jTextFieldCiudadOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCiudadOrigenActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldCiudadOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 280, 30));

        jSeparatorCiudadOrig.setBackground(new java.awt.Color(160, 160, 160));
        jPanel3.add(jSeparatorCiudadOrig, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 280, 10));

        jSpinner1.setFont(new java.awt.Font("Decker", 0, 17)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel3.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 190, 30));

        jLabelFechaIngreso.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabelFechaIngreso.setForeground(new java.awt.Color(51, 51, 51));
        jLabelFechaIngreso.setText("Fecha Salida:");
        jPanel3.add(jLabelFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 190, 30));

        jDateChooserSalida.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooserSalida.setForeground(new java.awt.Color(102, 102, 102));
        jDateChooserSalida.setEnabled(false);
        jDateChooserSalida.setFont(new java.awt.Font("Dubai", 0, 17)); // NOI18N
        jPanel3.add(jDateChooserSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 190, 30));

        jLabelFechaIngreso1.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabelFechaIngreso1.setForeground(new java.awt.Color(51, 51, 51));
        jLabelFechaIngreso1.setText("Fecha ingreso:");
        jPanel3.add(jLabelFechaIngreso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 190, 30));

        jSeparatorCiudadOrig1.setBackground(new java.awt.Color(214, 173, 96));
        jSeparatorCiudadOrig1.setForeground(new java.awt.Color(214, 173, 96));
        jSeparatorCiudadOrig1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparatorCiudadOrig1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 10, 430));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton_off.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton_on.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton_on.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton_on.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton_on.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 120, 40));

        jCheckBoxDosExtra.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxDosExtra.setFont(new java.awt.Font("Decker", 0, 17)); // NOI18N
        jCheckBoxDosExtra.setForeground(new java.awt.Color(51, 51, 51));
        jCheckBoxDosExtra.setText("2 personas extra");
        jCheckBoxDosExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDosExtraActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBoxDosExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 170, 30));

        jCheckBoxUnaExtra.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxUnaExtra.setFont(new java.awt.Font("Decker", 0, 17)); // NOI18N
        jCheckBoxUnaExtra.setForeground(new java.awt.Color(51, 51, 51));
        jCheckBoxUnaExtra.setText("1 persona extra");
        jCheckBoxUnaExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxUnaExtraActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBoxUnaExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 160, 30));

        jLabelPersonas2.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabelPersonas2.setForeground(new java.awt.Color(51, 51, 51));
        jLabelPersonas2.setText("Tipo de habitacion:");
        jPanel3.add(jLabelPersonas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 190, 30));

        jComboBoxPersonas.setFont(new java.awt.Font("Decker", 0, 17)); // NOI18N
        jComboBoxPersonas.setForeground(new java.awt.Color(51, 51, 51));
        jComboBoxPersonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel3.add(jComboBoxPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 280, 30));

        jScrollPane2.setBorder(null);

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(255, 0, 51));
        jScrollPane2.setViewportView(jTextPane1);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 620, 70));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 550));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setToolTipText("");

        jPanelDisponibles.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDisponibles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(jPanelDisponibles);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 510, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusLost
        this.jSeparatorNombre.setForeground(new Color(160, 160, 160));
        this.jSeparatorNombre.setBackground(new Color(160, 160, 160));
    }//GEN-LAST:event_jTextFieldNombreFocusLost

    private void jTextFieldNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusGained
        this.jSeparatorNombre.setForeground(new Color(214, 173, 96));
        this.jSeparatorNombre.setBackground(new Color(214, 173, 96));
    }//GEN-LAST:event_jTextFieldNombreFocusGained

    private void jTextFieldCiudadOrigenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCiudadOrigenFocusGained
        this.jSeparatorCiudadOrig.setForeground(new Color(214, 173, 96));
        this.jSeparatorCiudadOrig.setBackground(new Color(214, 173, 96));
    }//GEN-LAST:event_jTextFieldCiudadOrigenFocusGained

    private void jTextFieldCiudadOrigenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCiudadOrigenFocusLost
        this.jSeparatorCiudadOrig.setForeground(new Color(160, 160, 160));
        this.jSeparatorCiudadOrig.setBackground(new Color(160, 160, 160));
    }//GEN-LAST:event_jTextFieldCiudadOrigenFocusLost

    private void jTextFieldCiudadOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCiudadOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCiudadOrigenActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked
    public Date sumarRestarDiasFecha(Date fecha, int dias) {
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(fecha); // Configuramos la fecha que se recibe
        calendar.add(Calendar.DAY_OF_YEAR, dias);  // numero de días a añadir, o restar en caso de días<0
        return calendar.getTime(); // Devuelve el objeto Date con los nuevos días añadidos
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.jPanelDisponibles.removeAll();
        this.jPanelDisponibles.updateUI();
        this.botones.clear();
        this.jTextPane1.setText("");
        this.jDateChooserSalida.setDate(null);
        if (this.jTextFieldCiudadOrigen.getText().isEmpty() || this.jTextFieldNombre.getText().isEmpty()
                || this.jDateChooserIngreso.getDate() == null) {
            this.jTextPane1.setText("Error!\n No puede dejar campos vacios!");
            return;
        }
        int personas = this.jComboBoxPersonas.getSelectedIndex() + 1;
        int cupo = this.jComboBoxTipo.getSelectedIndex() + 1;
        int extra = 0;
        if (this.jCheckBoxUnaExtra.isSelected()) {
            extra = 1;
        }
        if (this.jCheckBoxDosExtra.isSelected()) {
            extra = 2;
        }
        if ((cupo + extra) < personas) {
            this.jTextPane1.setText("No se puede alojar esa cantidad de personas\n"
                    + "Intente seleccionar cargo por persona extra y/o sugerir cambio de tipo de habitacion");
            return;
        }

        this.jDateChooserSalida.setDate(sumarRestarDiasFecha(this.jDateChooserIngreso.getDate(), (int) this.jSpinner1.getValue()));
        String query = "select * from habitacion where tipo =  '" + (this.jComboBoxTipo.getSelectedIndex() + 1) + "'";
        this.conn.Consult(query);
        int x = 20, y = 40;
        int i = 0;
        try {
            if (this.conn.rs.getRow() == 0) {
                JOptionPane.showMessageDialog(null, "No hay elementos en la lista o no se pudo realizar la conexion");
                return;
            }
            while (this.conn.rs != null) {
                if(i==02){
                    x=20; y+=150;
                    i=0;
                }
                int habitacion = this.conn.rs.getInt("numero");
                
                boolean ocupado = this.conn.rs.getBoolean("estado");
                JButton boton = new JButton("Habitacion " + habitacion);
                boton.setName("Habitacion " + habitacion);
               
                boton.setBounds(x, y, 220, 130);
                boton.setVisible(true);
                if (ocupado) {
                    boton.setEnabled(false);
                }
                boton.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        botonDinamicoActionPerformed(e);
                    }
                });
                //this.jPanelDisponibles.getLayout().addLayoutComponent(boton.getName(), boton);
                //this.jPanelDisponibles.add(boton);
                this.jPanelDisponibles.add(boton, new AbsoluteConstraints(x,y,220,130));
                this.botones.add(boton);
                this.jPanelDisponibles.updateUI();
                i++;
                x+=240; 
                try {
                    this.conn.rs.next();
                } catch (Exception e) {

                }

            }
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private void botonDinamicoActionPerformed(java.awt.event.ActionEvent evt) {
        String x =  evt.getActionCommand();
        int numeroHab = Integer.parseInt(x.substring(11, 14));
        
        
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Seleccionar la habitacion " + numeroHab +"?", "Confirmar", dialog);
        if (result == 0) {
            String query = "UPDATE habitacion "
                    + "SET estado = 1 WHERE numero = " + numeroHab;
            int j=  this.conn.Update(query);
            if (j==0){
                this.jTextPane1.setText("No se ha realizado la operacion");
                
            }
            else{
                this.jTextPane1.setForeground(Color.GREEN);
                this.jTextPane1.setText("Registro Concretado");
                
            }
        }
    }
    private void jCheckBoxUnaExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxUnaExtraActionPerformed
        if (this.jCheckBoxUnaExtra.isSelected())
            this.jCheckBoxDosExtra.setSelected(false);
    }//GEN-LAST:event_jCheckBoxUnaExtraActionPerformed

    private void jCheckBoxDosExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDosExtraActionPerformed
        if (this.jCheckBoxDosExtra.isSelected())
            this.jCheckBoxUnaExtra.setSelected(false);
    }//GEN-LAST:event_jCheckBoxDosExtraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxDosExtra;
    private javax.swing.JCheckBox jCheckBoxUnaExtra;
    private javax.swing.JComboBox<String> jComboBoxPersonas;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private com.toedter.calendar.JDateChooser jDateChooserIngreso;
    private com.toedter.calendar.JDateChooser jDateChooserSalida;
    private javax.swing.JLabel jLabelCiudadOrigen;
    private javax.swing.JLabel jLabelFechaIngreso;
    private javax.swing.JLabel jLabelFechaIngreso1;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPersonas;
    private javax.swing.JLabel jLabelPersonas1;
    private javax.swing.JLabel jLabelPersonas2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelDisponibles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparatorCiudadOrig;
    private javax.swing.JSeparator jSeparatorCiudadOrig1;
    private javax.swing.JSeparator jSeparatorNombre;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextFieldCiudadOrigen;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
